server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RemoveRequestHeader=Cookie
            
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**

        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/parkings/**
        
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
jwt:
  secret: y7QaqaCDb+t0Tv2ISoLLXwPPZ3BCM5FwNO1fUxOnNHE3iUi36JQMebsKMYU5UzmrOzjxBkAxLzUjrv/QZ+Uzgw==

app:
  base-url: http://localhost:8080 
